<?php
/**
 * This is the default template for the
 * super-widget-cart items loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-cart directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_cart_before_items_loop' ); ?>
<div class="cart-item">
	<?php do_action( 'it_exchange_super_widget_cart_begin_items_loop' ); ?>
	<div class="title-remove">
		<?php foreach( it_exchange_get_template_part_elements( 'super_widget_cart', 'item-title-remove', array( 'item-title', 'item-remove' ) ) as $detail ) : ?>
			<?php it_exchange_get_template_part( 'super-widget-cart/elements/' . $detail ); ?>
		<?php endforeach; ?>
	</div>
	<div class="item-info">
		<?php foreach( it_exchange_get_template_part_elements( 'super_widget_cart', 'item-info', array( 'item-price' ) ) as $detail ) : ?>
			<?php it_exchange_get_template_part( 'super-widget-cart/elements/' . $detail ); ?>
		<?php endforeach; ?>
	</div>
	<?php do_action( 'it_exchange_super_widget_cart_end_items_loop' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_cart_after_items_loop' ); ?>
