<?php
/**
 * Default template for displaying the a single
 * invoice product header template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
 */
?>
<?php do_action( 'it_exchange_content_invoice_product_before_header_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-header it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_header_wrap' ); ?>
	<div class="it-exchange-left">
		<?php it_exchange( 'invoice', 'issued-date' ); ?>
		<?php
		if ( it_exchange( 'invoice', 'has-paid-date' ) )
			it_exchange( 'invoice', 'paid-date' );
		?>
	</div>
	<div class="it-exchange-right">
		<?php
		if ( it_exchange( 'invoice', 'has-invoice-number' ) ) :
			it_exchange( 'invoice', 'invoice-number', array( 'label' => 'Tax Invoice #' ) );
		endif;
		?>
		<?php
		if ( it_exchange( 'invoice', 'has-po-number' ) ) :
			it_exchange( 'invoice', 'po-number' );
		endif;
		?>
	</div>
	<?php do_action( 'it_exchange_content_invoice_product_end_header_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_header_wrap' ); ?>
