<?php
/**
 * Default template for displaying the a single
 * invoice product to and from template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
 */
?>
<?php do_action( 'it_exchange_content_invoice_product_before_to-from_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-to-from it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_to-from_wrap' ); ?>
	<div class="it-exchange-left">
		<?php it_exchange( 'invoice', 'to' ); ?>
	</div>
	<div class="it-exchange-right">
		<?php it_exchange( 'invoice', 'from', array(
			'fields' => array(
			  'company',
			  'address',
			  'email'
			)
		  )
		); ?>
	</div>
	<?php do_action( 'it_exchange_content_invoice_product_end_to-from_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_to-from_wrap' ); ?>
