<?php
/**
 * This is the default template part for the
 * guest-checkout element in the super-widget-login template
 * part.
 *
 * @since 1.6.0
 * @version 1.6.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-login/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_login_before_guest_checkout_link_element' ); ?>
<?php echo it_exchange_guest_checkout_sw_link( __( 'Check out as a guest', 'it-l10n-ithemes-exchange' ) ); ?>
<?php do_action( 'it_exchange_super_widget_login_after_guest_checkout_link_element' ); ?>
