<?php
/**
 * This is the default template for the
 * super-widget-cart item-price element.
 *
 * @since 1.1.0
 * @version 1.6.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-cart/elements directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_cart_before_item_price_element' ); ?>
<?php if ( it_exchange( 'cart-item', 'has-purchase-quantity' ) && 'coupon' != it_exchange( 'cart', 'get-focus' ) ) : ?>
	<?php it_exchange( 'cart-item', 'price' ); ?> &times; <?php it_exchange( 'cart-item', 'quantity' ); ?>
<?php else : ?>
	<?php if ( it_exchange( 'cart-item', 'get-quantity', array( 'format' => 'var_value' ) ) > 1 ) : ?>
		<?php it_exchange( 'cart-item', 'price' ); ?> &times; <?php it_exchange( 'cart-item', 'quantity', array( 'format' => 'var_value' ) ); ?> &#61; <?php it_exchange( 'cart-item', 'subtotal' ); ?>
	<?php else : ?>
		<?php it_exchange( 'cart-item', 'price' ); ?>
	<?php endif; ?>
<?php endif; ?>
<?php do_action( 'it_exchange_super_widget_cart_after_item_price_element' ); ?>
