<?php
/**
 * This is the default template for the
 * super-widget-cart-remove element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-cart/elements directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_cart_before_item_remove_element' ); ?>
<?php it_exchange( 'cart-item', 'remove' ); ?>
<?php do_action( 'it_exchange_super_widget_cart_after_item_remove_element' ); ?>
