<?php
/**
 * The default template part for the welcome message in
 * the content-memberships template part's content loop
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package IT_Exchange_Addon_Membership
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-memberships/elements/ directory
 * located in your theme.
*/
?>

<?php if ( it_exchange( 'member-dashboard', 'has-welcome-message' ) ) : ?>
	<?php do_action( 'it_exchange_membership_addon_content_memberships_before_welcome_element' ); ?>
	<div class="it-exchange-membership-welcome-message it-exchange-advanced-item">
    <p><?php it_exchange( 'member-dashboard', 'welcome-message' ); ?></p>
	</div>
	<?php do_action( 'it_exchange_membership_addon_content_memberships_after_welcome_element' ); ?>
<?php endif; ?>