<?php
/**
 * This is the default template part for the
 * content loop in the content-account
 * template part.
 *
 * @since 1.4.0
 * @version 1.4.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-account/loops/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_surveys_before_content_loop' ); ?>
	<div class="it-exchange-customer-info">
	<?php do_action( 'it_exchange_content_surveys_begin_content_loop' ); ?>
		<div class="container">
			<div class="row">
				<div class="span8">		
					<h2>Surveys</h2>
					<?php
					$args = array(
						'post_type'      => 'survey',
						'meta_key'       => '_survey_ended',
						'meta_value' => 'no',
						'order'          => 'ASC',
						'posts_per_page' => 100,
					);
					
					$new = new WP_Query($args);
					if ( have_posts() ) : while ($new->have_posts()) : $new->the_post(); ?>	
			
						<h3><?php the_title(); ?></h3>
						<?php the_content(); ?>
					<?php endwhile; else: ?>
					<div class="row">
						<div class="span8">
							<p><?php _e('Sorry, no surveys added yet.'); ?></p>
						</div>
					</div>	
					<?php endif; ?>	
					<!-- ended surveys -->
					
					<hr />
					<h2>Ended Surveys</h2>
					<?php
					$args = array(
						'post_type'      => 'survey',
						'meta_key'       => '_survey_ended',
						'meta_value' => 'yes',
						'order'          => 'ASC',
						'posts_per_page' => 100,
					);
					
					$new = new WP_Query($args);
					if ( have_posts() ) : while ($new->have_posts()) : $new->the_post(); ?>	
					
						<h3><?php the_title(); ?></h3>
						<?php the_content(); ?>
					<?php endwhile; else: ?>
					<div class="row">
						<div class="span8">
							<p><?php _e('Sorry, no ended surveys yet.'); ?></p>
						</div>
					</div>	
					<?php endif; ?>						
				</div>
				<div class="span4">
					<?php get_sidebar(); ?>	
				</div>
			</div>

	<?php do_action( 'it_exchange_content_surveys_end_content_loop' ); ?>
	</div>
<?php do_action( 'it_exchange_content_surveys_after_content_loop' ); ?>
