<?php
/**
 * This is the default template part for the
 * no-products-found message in the content-store
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-store/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_store_before_no_products_found_element' ); ?>
<p class="it-exchange-no-product-found it-exchange-notice">
	<?php _e( 'No Products Found', 'it-l10n-ithemes-exchange' ); ?>
</p>
<?php do_action( 'it_exchange_content_store_after_no_products_found_element' ); ?>