<?php
/**
 * The default template part for the product title in
 * the content-store template part's product-info loop
 *
 * @since 1.1.0
 * @version 1.2.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-store/elements
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_store_info_before_title_element' ); ?>
<h2 class="it-exchange-product-title entry-title">
	<a href="<?php it_exchange( 'product', 'permalink', array( 'format' => 'url' ) ); ?>"><?php it_exchange( 'product', 'title', array( 'format' => 'text' ) ); ?></a>
</h2>
<?php do_action( 'it_exchange_content_store_info_after_title_element' ); ?>
