<?php
/**
 * This is the default template for the
 * super-widget-checkout billing-address element.
 *
 * @since 1.3.0
 * @version 1.3.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_billing_address_existing_element' ); ?>
<div class="cart-billing-address-existing cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_billing_address_existing_element' ); ?>
	<strong><?php _e( 'Billing Address:', 'it-l10n-ithemes-exchange' ); ?></strong> <a href="" class="it-exchange-sw-edit-billing-address"><?php _e( 'Edit', 'it-l10n-ithemes-exchange' ); ?></a><br/>
	<?php echo it_exchange_get_formatted_billing_address(); ?><br />
	<?php do_action( 'it_exchange_super_widget_checkout_end_billing_address_existing_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_billing_address_existing_element' ); ?>
