<?php
/**
 * This is the default template for the
 * super-widget-checkout transaction-methods loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_checkout_before_transaction_methods' ); ?>
<div class="payment-methods-wrapper">
	<?php if ( ! it_exchange( 'checkout', 'has-transaction-methods' ) ) : ?>
		<p><?php _e( 'No payment add-ons enabled.', 'it-l10n-ithemes-exchange' ); ?></p>
	<?php else : ?>
		<?php do_action( 'it_exchange_content_checkout_before_transaction_methods_loop' ); ?>
		<?php while( it_exchange( 'checkout', 'transaction-methods' ) ) : ?>
		<?php do_action( 'it_exchange_content_checkout_begin_transaction_methods_loop' ); ?>
			<?php it_exchange( 'transaction-method', 'make-payment' ); ?>
		<?php do_action( 'it_exchange_content_checkout_end_transaction_methods_loop' ); ?>
		<?php endwhile; ?>
		<?php do_action( 'it_exchange_content_checkout_after_transaction_methods_loop' ); ?>
	<?php endif; ?>
</div>
<?php do_action( 'it_exchange_content_checkout_after_transaction_methods' ); ?>
