<?php
/**
 * This is the default template part for the
 * customer menu in the transaction
 * confirmation template part.
 *
 * @since 1.4.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_confirmation_before_transaction_customer_menu' ); ?>
<div class="it-exchange-customer-menu-wrapper">
	<?php it_exchange( 'customer', 'menu' ); ?>
</div>
<?php do_action( 'it_exchange_confirmation_after_transaction_customer_menu' ); ?>