<?php
/**
 * This is the default template part for the
 * register element in the super-widget-guest-checkout template
 * part located in the core-addons/admin/guest-checkout/lib/templates directory
 *
 * @since 1.6.0
 * @version 1.6.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-guest-checkout/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_guest_checkout_before_register_elements' ); ?>
<div class="register_url">
	<a class="it-exchange-sw-register-link" href="<?php esc_attr_e( it_exchange( 'login', 'get-register', array( 'format' => 'url' ) ) ); ?>"><input type="button" value="<?php esc_attr( _e( 'Create an account', 'it-l10n-ithemes-exchange' ) ); ?>" /></a>
</div>
<?php do_action( 'it_exchange_super_widget_guest_checkoutafter_register_elements' ); ?>
