<?php
/**
 * This is the default template for the
 * super-widget-billing-address actions loop.
 *
 * @since 1.3.0
 * @version 1.3.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-billing-address/loops directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_billing_address_before_actions_loop' ); ?>
<?php do_action( 'it_exchange_super_widget_billing_address_begin_actions_loop' ); ?>
<?php foreach ( it_exchange_get_template_part_elements( 'super_widget_billing-address', 'actions', array( 'submit', 'cancel' ) ) as $action ) : ?>
	<?php
	/**
	 * Theme and add-on devs should add code to this loop by
	 * hooking into it_exchange_get_template_part_elements filter
	 * and adding the appropriate template file to their theme or add-on
	 */
	it_exchange_get_template_part( 'super-widget', 'billing-address/elements/' . $action );
	?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_super_widget_billing_address_end_actions_loop' ); ?>
<?php do_action( 'it_exchange_super_widget_billing_address_after_actions_loop' ); ?>
