<?php
/**
 * This is the default template part for the
 * fields loop in the content-profile
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-profile/loops/ directory
 * located in your theme.
 */
?>

<?php do_action( 'it_exchange_content_profile_before_fields_loop' ); ?>
<div class="it-exchange-customer-info">
	<?php do_action( 'it_exchange_content_profile_begin_fields_loop' ); ?>
	<?php $fields = array( 'first-name', 'last-name', 'email', 'website', 'password1', 'password2' ); ?>
	<?php foreach ( it_exchange_get_template_part_elements( 'content_profile', 'fields', $fields ) as $key => $field ) : ?>

		<?php if ( $key == 0 ) : ?>
			<div class="input-row">
		<?php elseif ( $key % 2 == 0 ) : ?>
			<div class="input-row">
		<?php endif; ?>

		<div class="pull-left">
			<?php it_exchange_get_template_part( 'content-profile/elements/' . $field ); ?>
		</div>

		<?php if ( $key == count( $fields ) ) : ?>
			</div>
		<?php elseif ( $key % 2 == 1 ) : ?>
			</div>
		<?php endif; ?>

	<?php endforeach; ?>
	<?php do_action( 'it_exchange_content_profile_end_fields_loop' ); ?>
	</div>
<?php do_action( 'it_exchange_content_profile_after_fields_loop' ); ?>
