<?php
/**
 * Default template for displaying the an exchange
 * customer's purchase(s).
 *
 * @since 0.4.0
 * @version 1.0.1
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>

<?php do_action( 'it_exchange_content_purchases_before_wrap' ); ?>
<div id="it-exchange-purchases" class="it-exchange-wrap it-exchange-account">
<?php do_action( 'it_exchange_content_purchases_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php it_exchange( 'customer', 'menu' ); ?>

	<?php if ( it_exchange( 'transactions', 'found' ) ) : ?>
		<?php it_exchange_get_template_part( 'content-purchases/loops/transactions' ); ?>
	<?php else : ?>
		<?php it_exchange_get_template_part( 'content-purchases/elements/no-purchases-found' ); ?>
	<?php endif; ?>
<?php do_action( 'it_exchange_content_purchases_end_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_purchases_after_wrap' ); ?>