<?php
/**
 * This is the default template part for the
 * checkout element in the content-cart template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_cart_before_checkout_element' ); ?>
<?php it_exchange( 'cart', 'checkout' ); ?>
<?php do_action( 'it_exchange_content_cart_after_checkout_element' ); ?>