<?php
/**
 * This is the default template part for the
 * continue_shopping element in the content-cart template
 * part.
 *
 * @since 1.8.1
 * @version 1.8.1
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/ directory
 * located in your theme.
*/
?>
<?php if ( it_exchange( 'cart', 'has-continue-shopping' ) ) : ?>
<?php do_action( 'it_exchange_content_cart_before_continue_shopping_element' ); ?>
<?php it_exchange( 'cart', 'continue-shopping' ); ?>
<?php do_action( 'it_exchange_content_cart_after_continue_shopping_element' ); ?>
<?php endif; ?>
