<?php
/**
 * Default template for displaying the user login.
 * page.
 *
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/ directory located
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_login_before_wrap' ); ?>
<div id="it-exchange-login" class="it-exchange-wrap it-exchange-account">
<?php do_action( 'it_exchange_content_login_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<div class="it-exchange-login-form">
		<?php do_action( 'it_exchange_content_login_before_form' ); ?>
		<?php it_exchange( 'login', 'form-open' ); ?>
			<?php do_action( 'it_exchange_content_login_begin_form' ); ?>
			<?php it_exchange_get_template_part( 'content-login/loops/fields' ); ?>
			<?php it_exchange_get_template_part( 'content-login/loops/actions' ); ?>
			<?php do_action( 'it_exchange_content_login_end_form' ); ?>
		<?php it_exchange( 'login', 'form-close' ); ?>
		<?php do_action( 'it_exchange_content_login_after_form' ); ?>
	</div>
<?php do_action( 'it_exchange_content_login_end_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_login_after_wrap' ); ?>