<?php
/**
 * This is the default template for the
 * super-widget-checkout discounts loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_discounts_loop' ); ?>
<div class="cart-discount cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_discounts_loop' ); ?>
	<?php while( it_exchange( 'coupons', 'applied', array( 'type' => 'cart' ) ) ) : ?>
		<?php _e( 'Discount:', 'it-l10n-ithemes-exchange' ); ?> <?php it_exchange( 'coupons', 'discount-label' ); ?> <?php _e( 'OFF', 'it-l10n-ithemes-exchange' ); ?>
	<?php endwhile; ?>
	<?php do_action( 'it_exchange_super_widget_checkout_end_discounts_loop' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_discounts_loop' ); ?>
