<?php
/**
 * This is the default template for the
 * super-widget-cart applied-coupons loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-cart/loops directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_cart_before_applied_coupons_loop' ); ?>
<ul class="applied-coupons">
	<?php do_action( 'it_exchange_super_widget_cart_begin_applied_coupons_loop' ); ?>
	<?php while( it_exchange( 'coupons', 'applied', array( 'type' => 'cart' ) ) ) : ?>
		<li class="coupon">
			<?php it_exchange( 'coupons', 'code' ); ?> &ndash; <?php it_exchange( 'coupons', 'discount-label' ); ?>&nbsp;<?php it_exchange( 'coupons', 'remove', array( 'type' => 'cart' ) ); ?>
		</li>
	<?php endwhile; ?>
	<?php do_action( 'it_exchange_super_widget_cart_end_applied_coupons_loop' ); ?>
</ul>
<?php do_action( 'it_exchange_super_widget_cart_after_applied_coupons_loop' ); ?>
