<?php
/**
 * This is the default template part called by
 * content-registration when registration is
 * disabled.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-registration/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_registration_before_registration_disabled_message_element' ); ?>
<p class="it-exchange-registration-disabled it-exchange-notice">
	<?php it_exchange( 'registration', 'disabled-message' ); ?>
</p>
<?php do_action( 'it_exchange_content_registration_before_registration_disabled_message_element' ); ?>