<?php
/**
 * This is the default template part for the
 * actions loop in the guest-checkout purchase-requriements
 * in the content-checkout template part.
 *
 * @since 1.6.0
 * @version 1.6.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the
 * /exchange/content-checkout/elements/purchase-requirements/guest-checkout/loops/
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_checkout_guest_checkout_purchase_requirement_before_actions_loop' ); ?>
<?php $actions = array( 'continue' ); ?>
<?php foreach( it_exchange_get_template_part_elements( 'content-checkout-guest-checkout-purchase-requirement', 'actions', $actions ) as $action ) : ?>
	<?php
	/**
	 * Theme and add-on devs should add code to this loop by
	 * hooking into it_exchange_get_template_part_elements filter
	 * and adding the appropriate template file to their theme or add-on
	 */
	it_exchange_get_template_part( 'content', 'checkout/elements/purchase-requirements/guest-checkout/elements/' . $action );
	?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_content_checkout_guest_checkout_purchase_requirement_after_actions_loop' ); ?>
