<?php
/**
 * Default template for displaying the an exchange
 * customer's purchased journals.
 *
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/ directory located
 * in your theme.
 */
?>

<?php do_action( 'it_exchange_content_journals_before_wrap' ); ?>

	<div id="it-exchange-journals" class="it-exchange-wrap it-exchange-account">
	<?php do_action( 'it_exchange_content_journals_begin_wrap' ); ?>
		<?php it_exchange_get_template_part( 'messages' ); ?>
		<?php it_exchange( 'customer', 'menu' ); ?>

		<?php if ( it_exchange( 'journals', 'has-articles' ) ) : ?>

		<div class="table-responsive">
	        <table class="table">
		        <thead>
		            <tr>
			            <th>Article Name</th>
			            <th>Author</th>
			            <th>Published</th>
			            <th></th>
			            <th></th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
			            <th>Article Name</th>
			            <th>Author</th>
			            <th>Published</th>
			            <th></th>
			            <th></th>
		            </tr>
		        </tfoot>
		        <tbody>
				<?php while ( it_exchange( 'journals', 'articles' ) ) : ?>

					<?php it_exchange_get_template_part( 'content-journals/loops/fields' ); ?>

				<?php endwhile; ?>
		        </tbody>
		    </table>
		</div>
		<?php endif; ?>

		<?php do_action( 'it_exchange_content_journals_end_wrap' ); ?>
</div>

<?php do_action( 'it_exchange_content_journals_after_wrap' ); ?>