<?php
/**
 * This is the default template part for the
 * address2 element in the billing-address
 * purchase-requriements in the super-widget-billing-address template part.
 *
 * @since 1.3.0
 * @version 1.3.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the
 * /exchange/super-widget-billing-address/elements/
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_billing_address_purchase_requirement_before_address2_element' ); ?>
<div class="it-exchange-address2">
	<?php it_exchange( 'billing', 'address2', array( 'label' => false ) ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_billing_address_purchase_requirement_after_address2_element' ); ?>
