<?php
/**
 * The transactions loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/loops/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_confirmation_before_transactions_loop' ); ?>
<?php if ( it_exchange( 'transactions', 'found' ) ) : ?>
	<?php do_action( 'it_exchange_content_confirmation_begin_transactions_loop' ); ?>
	<?php while( it_exchange( 'transactions', 'exist' ) ) : ?>
		<?php it_exchange_get_template_part( 'content-confirmation/loops/transaction-meta' ); ?>
		<?php it_exchange_get_template_part( 'content-confirmation/loops/products' ); ?>
	<?php endwhile; ?>
	<?php do_action( 'it_exchange_content_confirmation_end_transactions_loop' ); ?>
<?php else : ?>
	<?php it_exchange_get_template_part( 'content-confirmation/elements/not-found' ); ?>
<?php endif; ?>
<?php do_action( 'it_exchange_content_confirmation_after_transactions_loop' ); ?>