<?php

/**
 *
 * @package Conferences
 * @subpackage Metabox
 * @since 6/2
 */
class LDMW_Conference_Metabox_Speakers extends LDMW_Conference_Metabox_Page {
	/**
	 * Remove the add media buttons for speakers
	 *
	 * @param string $title
	 * @param string $slug
	 * @param string $post_types
	 */
	public function __construct( $title, $slug = null, $post_types = null ) {
		parent::__construct( $title, $slug, $post_types );
		remove_filter( 'fm_element_markup_start', array( $this, 'add_media_buttons' ), 10, 2 );
	}

	/**
	 * Fetch a different template for speakers
	 *
	 * @param array $existing
	 *
	 * @return array
	 */
	public function fetch_template( $existing ) {
		return parent::fetch_template( $existing ); // TODO: Change the autogenerated stub
	}

	/**
	 * Register our speaker metabox
	 */
	protected function register_metabox() {
		$fm = new Fieldmanager_Group( array(
			'name'           => $this->slug,
			'tabbed'         => true,
			'limit'          => 0,
			'add_more_label' => 'Add another speaker',
			'children'       => array(
			  'name'        => new Fieldmanager_TextField( 'Name' ),
			  'image'       => new Fieldmanager_Media( 'Photo' ),
			  'position'    => new Fieldmanager_TextField( 'Position' ),
			  'description' => new Fieldmanager_RichTextArea( 'Description' )
			)
		  )
		);

		$fm->add_meta_box( $this->title, $this->post_types, 'normal', 'high' );
	}

	/**
	 * @return string
	 */
	protected function get_content() {
		return '';
	}

}