<?php
/**
 * This is the default template part for the
 * totals loop in the content-checkout
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/loops/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_checkout_before_totals' ); ?>
<div id="it-exchange-cart-totals" class="it-exchange-table">
<?php do_action( 'it_exchange_content_checkout_before_totals_loop' ); ?>
	<?php do_action( 'it_exchange_content_checkout_begi_totalsn_loop' ); ?>
		<?php foreach ( it_exchange_get_template_part_elements( 'content_checkout', 'totals', array( 'totals-subtotal', 'totals-savings', 'totals-total' ) ) as $totals ) : ?>
			<div class="it-exchange-table-row it-exchange-cart-<?php echo $totals; ?>">
				<?php
				/**
				 * Theme and add-on devs should add code to this loop by
				 * hooking into it_exchange_get_template_part_elements filter
				 * and adding the appropriate template file to their theme or add-on
				*/
				it_exchange_get_template_part( 'content-checkout/elements/' . $totals );
				?>
			</div>
		<?php endforeach; ?>
	<?php do_action( 'it_exchange_content_checkout_end_totals_loop' ); ?>
<?php do_action( 'it_exchange_content_checkout_before_totals_loop' ); ?>
</div>
<?php do_action( 'it_exchange_content_checkout_after_totals' ); ?>