<?php
/**
 * The default dashboard loop for the content-membership.php template part
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange_Addon_Membership
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-purchases/loops/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_membership_addon_content_memberships_before_content_loop' ); ?>
<?php do_action( 'it_exchange_membership_addon_content_memberships_start_content_loop' ); ?>
<?php foreach ( it_exchange_get_template_part_elements( 'content_memberships', 'available_content', array( 'welcome-message', 'membership-content' ) ) as $detail ) : ?>
	<?php it_exchange_get_template_part( 'content-memberships/elements/' . $detail ); ?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_membership_addon_content_memberships_end_content_loop' ); ?>
<?php do_action( 'it_exchange_membership_addon_content_memberships_after_content_loop' ); ?>