<?php
/**
 * The default template part for the product included confmirmation in
 * the content-confirmation template part's products loop
 *
 * @since 1.0.0
 * @version 1.2.0
 * @package IT_Exchange_Addon_Membership
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange-addon-membership/lib/templates/content-confirmation/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_confirmation_before_membership_confirmation_element' ); ?>
<div class="it-exchange-item-membership-confirmation-content it-exchange-clearfix">
	<span><?php it_exchange( 'membership-confirmation', 'dashboard-link' ); ?></span>
</div>
<?php do_action( 'it_exchange_content_confirmation_after_membership_confirmation_element' ); ?>