<?php
/**
 * The default template part for the download's
 * download url in the content-downloads template
 * part's download-info loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-downloads/elements
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_download_before_download_url_element' ); ?>
<?php if ( ! it_exchange( 'transaction', 'get-product-download-hash', array( 'attribute' => 'download-limit' ) ) || it_exchange( 'transaction', 'get-product-download-hash', array( 'attribute' => 'downloads-remaining' ) ) ) : ?>
	<?php if ( it_exchange( 'transaction', 'get-cleared-for-delivery' ) ) : ?>
		<span class="it-exchange-download-now">
			<a href="<?php it_exchange( 'transaction', 'product-download-hash', array( 'attribute' => 'download-url' ) ); ?>"><?php _e( 'Download Now', 'it-l10n-ithemes-exchange' ); ?></a>
		</span>
	<?php endif; ?>
<?php endif; ?>
<?php do_action( 'it_exchange_content_download_after_download_url_element' ); ?>