<?php
/**
 * This is the default template part for the
 * checkout element in the content-checkout
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_checkout_before_transaction_methods_element' ); ?>
<div class="it-exchange-checkout-transaction-methods">
	<?php if ( ! it_exchange( 'checkout', 'has-transaction-methods' ) ) : ?>
		<p><?php _e( 'No Payment add-ons enabled.', 'it-l10n-ithemes-exchange' ); ?></p>
	<?php else : ?>
		<?php while( it_exchange( 'checkout', 'transaction-methods' ) ) : ?>
			<?php it_exchange( 'transaction-method', 'make-payment' ); ?>
		<?php endwhile; ?>
	<?php endif; ?>
</div>
<?php do_action( 'it_exchange_content_checkout_actions_after_transaction_methods_element' ); ?>