<?php
/**
 * This is the default template part for the
 * register element in the super-widget-login template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-login/elements
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_login_before_register_element' ); ?>
<div class="it-exchange-register-url">
	<a class="it-exchange-sw-register-link exchange-button" href="<?php esc_attr_e( it_exchange( 'login', 'get-register', array( 'format' => 'url' ) ) ); ?>"><input type="button" value="<?php esc_attr_e( __( 'Create an account', 'it-l10n-ithemes-exchange' ) ); ?>" /></a>
</div>
<?php do_action( 'it_exchange_super_widget_login_after_register_element' ); ?>
