<?php
/**
 * This is the default template part for the core shipping-method
 * purchase requirement element in the content-checkout
 * template part.
 *
 * @since 1.4.0
 * @version 1.4.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/purchase-requirements directory
 * located in your theme.
*/

// Don't show anything if shipping-method requirement exists and hasn't been met
if ( in_array( 'shipping-address', it_exchange_get_pending_purchase_requirements() ) )
	return;
?>

<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_before_element' ); ?>
<div class="it-exchange-checkout-shipping-method-purchase-requirement">
	<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_begin_element' ); ?>

	<h3><?php _e( 'Shipping Method', 'it-l10n-ithemes-exchange' ); ?></h3>
	<?php it_exchange( 'shipping-method', 'form' ); ?>

	<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_end_element' ); ?>
</div>
<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_after_element' ); ?>
