<?php
/**
 * This is the default template for the
 * super-widget-checkout item element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/elements directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_checkout_before_item_element' ); ?>
<div class="cart-item">
    <?php do_action( 'it_exchange_super_widget_checkout_begin_item_element' ); ?>
    <div class="title-remove">
        <?php foreach( it_exchange_get_template_part_elements( 'super_widget_checkout', 'item-title', array( 'title', 'remove' ) ) as $detail ) : ?>
            <?php it_exchange_get_template_part( 'super-widget-checkout/elements/' . $detail ); ?>
        <?php endforeach; ?>
    </div>
    <div class="item-info">
        <?php foreach( it_exchange_get_template_part_elements( 'super_widget_checkout', 'item-info', array( 'price' ) ) as $detail ) : ?>
            <?php it_exchange_get_template_part( 'super-widget-checkout/elements/' . $detail ); ?>
        <?php endforeach; ?>
    </div>
    <?php do_action( 'it_exchange_super_widget_checkout_end_item_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_item_element' ); ?>