<?php
/**
 * This is the default template for the
 * super-widget-checkout multi-item-cancel element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/elements directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_checkout_before_multi_item_cancel_element' ); ?>
<div class="cart-action view-cart">
	<?php it_exchange( 'checkout', 'cancel', array( 'label' => __( 'View Cart', 'it-l10n-ithemes-exchange' ) ) ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_multi_item_cancel_element' ); ?>
