<?php
/**
 * This is the default template part for the
 * country element in the shipping-address
 * purchase-requriements in the super-widget-shipping-address template part.
 *
 * @since 1.4.0
 * @version 1.4.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the
 * /exchange/super-widget-shipping-address/elements/
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_shipping_address_purchase_requirement_before_country_element' ); ?>
<div class="it-exchange-country">
	<?php it_exchange( 'shipping', 'country' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_shipping_address_purchase_requirement_after_country_element' ); ?>
