<?php
/**
 * Default template for displaying the user login.
 * page.
 *
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/content-login.php
*/
?>

<?php it_exchange_get_template_part( 'messages' ); ?>

<div id="it-exchange-customer">
	<div class="login">
		<?php it_exchange( 'login', 'form-open' ); ?>
			<div class="user-name">
				<?php it_exchange( 'login', 'username' ); ?>
			</div>
			<div class="password">
				<?php it_exchange( 'login', 'password' ); ?>
			</div>
			<div class="rememberme">
				<?php it_exchange( 'login', 'rememberme' ); ?>
			</div>
			<?php it_exchange( 'login', 'login-button' ); ?>
			<div class="recover_url">
				<?php it_exchange( 'login', 'recover' ); ?>
			</div>
			<div class="register_url">
				<?php it_exchange( 'login', 'register' ); ?>
			</div>
		<?php it_exchange( 'login', 'form-close' ); ?>
	</div>
</div>
