<?php
/**
 * This is the default template part for a
 * product in the store.
 *
 * @since 0.4.0
 * @version 1.0.2
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/store-product.php
*/
?>
<li class="it-exchange-product">
	<?php if ( it_exchange( 'product', 'has-featured-image' ) ) : ?>
		<a class="it-exchange-product-permalink" href="<?php it_exchange( 'product', 'permalink', array( 'format' => 'url') ); ?>">
			<?php it_exchange( 'product', 'featured-image', array( 'size' => 'large' ) ); ?>
		</a>
	<?php endif; ?>
	<div class="it-exchange-product-details">
		<?php it_exchange( 'product', 'title' ); ?>
		<?php it_exchange( 'product', 'baseprice' ); ?>
		<a class="it-exchange-product-details-link" href="<?php it_exchange( 'product', 'permalink', array( 'format' => 'url') ); ?>"><?php _e( 'View Details', 'it-l10n-ithemes-exchange' ); ?></a>
	</div>
</li>
