<?php
/**
 * The login template for the Super Widget.
 *
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/super-widget-login.php
*/
?>

<?php it_exchange_get_template_part( 'messages' ); ?>

<div class="login it-exchange-sw-processing-login">
	<?php it_exchange( 'login', 'formopen' ); ?>
		<div class="user-name">
			<?php it_exchange( 'login', 'username' ); ?>
		</div>
		<div class="password">
			<?php it_exchange( 'login', 'password' ); ?>
		</div>
		<div class="rememberme">
			<?php it_exchange( 'login', 'remember-me' ); ?>
		</div>
		<?php it_exchange( 'login', 'login-button' ); ?>
		<div class="recover_url">
			<?php it_exchange( 'login', 'recover' ); ?>
		</div>
		<div class="register_url">
			<?php it_exchange( 'login', 'register' ); ?>
		</div>
		<div class="cancel_url">
			<?php it_exchange( 'login', 'cancel' ); ?>
		</div>
	<?php it_exchange( 'login', 'form-close' ); ?>
</div>
